<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/layout.php';
Auth::requireRole('student');
Auth::refresh();
$user = Auth::user();
$courseIds = array_map('intval', array_column(courses_for_student($user), 'id'));
$ppts = [];
if ($courseIds) {
    $in = implode(',', array_fill(0, count($courseIds), '?'));
    $params = $courseIds;
    $params[] = (int)$user['institution_id'];
    $ppts = Database::fetchAll(
        "SELECT p.id, p.title, p.slide_count, p.status,
                s.name AS subject_name, s.code AS subject_code,
                u.full_name AS professor_name
         FROM presentations p
         LEFT JOIN course_plans cp ON cp.id = p.plan_id
         LEFT JOIN subjects s ON s.id = COALESCE(p.subject_id, cp.subject_id)
         LEFT JOIN users u ON u.id = p.professor_id
         WHERE p.status IN (\"ready\",\"published\")
           AND COALESCE(p.subject_id, cp.subject_id) IN ($in)
           AND s.institution_id = ?
         ORDER BY p.id DESC",
        $params
    );
}
render_header('Course PPT', 'notes');
?>
<div class="panel">
  <h2>Presentations</h2>
  <?php if (!$ppts): ?><div class="empty">No PPTs shared yet.</div><?php endif; ?>
  <?php foreach ($ppts as $p):
    $courseName = trim((string)($p['subject_name'] ?? ''));
    $courseCode = trim((string)($p['subject_code'] ?? ''));
    $courseLine = $courseName;
    if ($courseName !== '' && $courseCode !== '') {
        $courseLine = $courseName . ' · ' . $courseCode;
    } elseif ($courseCode !== '') {
        $courseLine = $courseCode;
    }
    $prof = trim((string)($p['professor_name'] ?? ''));
  ?>
    <div class="student-ppt-row">
      <div class="student-ppt-meta">
        <?php if ($courseLine !== ''): ?>
          <strong class="student-ppt-course"><?= e($courseLine) ?></strong>
        <?php endif; ?>
        <div class="student-ppt-title"><?= e((string)$p['title']) ?></div>
        <div class="student-ppt-slides"><?= (int)$p['slide_count'] ?> slides</div>
        <?php if ($prof !== ''): ?>
          <div class="student-ppt-by">Generated by: <?= e($prof) ?></div>
        <?php endif; ?>
      </div>
      <a class="btn btn-sm btn-primary" href="<?= e(base_url('/professor/ppt-view.php?id='.$p['id'])) ?>">View</a>
    </div>
  <?php endforeach; ?>
</div>
<?php render_footer(); ?>
